version: '3.8'

services:
  web:
    image: my-node-app
    networks:
      - webnet
    ports:
      -"3000:3000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - webnet

networks:
  webnet: